### ISSUE TITLE
Any way to delete an entry / mass delete lines?

### ISSUE THREAD

**Issue by SpacemanSpiff357** [KamWithK/exSTATic#22]
I messed up a hook that fed a bunch of junk text into exstatic, deleting it 1 by 1 would take too long so I was wondering if I could just scrap the whole entry or if there was a more efficient way to delete the junk lines

**Comment by SpacemanSpiff357** [comment]
Never mind - saw you could edit the data manually

**Comment by KamWithK** [comment]
Good to know you managed to fix your problem!
By the way though, you should be able to select many lines and hit delete, you don't have to delete one line at a time

**Comment by oubagaku** [comment]
Related to this, when I open a VN to test out how textractor functions with that particular VN, sometimes I forget to close the tracker.html page or disable the extension so I end up with a bunch of lines for a VN I might not end up playing. Even after deleting all the lines, when going to the stats page, I see a VN with 0 chars read and a few minutes of time played that makes the stats look ugly and filled with a bunch of junk 0 chars read VNs. This is fixed by manually editing the data, but it's a bit of a pain. I will see if I can do a PR. Maybe a "Delete entries with 0 Characters" button or maybe a more general way to somehow select an entry and delete it so it is more generally useful?
