### ISSUE TITLE
Support for accepting raw text strings

### ISSUE THREAD

**Issue by pinntokuru** [KamWithK/exSTATic#24]
Currently exSTATic seems to accept lines in a specific json format. Sending regular text lines, for example lines captured from OCR programs such as mangaOCR, does not work. 

Adding support for this would enable exSTATic to be used by a wide variety of apps other than just Textractor and in my opinion future proof it in case Textractor stops working or becomes obsolete for whatever reason.

**Comment by KamWithK** [comment]
There are reasons for having the input be in json instead of regular text:
1. JSON is a human readable standard for providing data with structure, everyone is familiar with it and can implement simplified string-ification even if they don't have a JSON library available
2. Within the JSON we can provide information like the current program being hooked which wouldn't otherwise be feasible, this provides auto switching between VNs and ensures you don't accidentally start hooking in the wrong place
3. exSTATic is not limited to Textractor, it has for a long while had support for Agent and recently earlier this year I added clipboard support via a companion executable
4. Clipboard support does give support for plain text already

I don't think exSTATic needs this to be "future proofed" in this manor as it's reasonable to expect future developers to support returning a JSON string like this
